# Generated by Django 4.2.3 on 2023-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('primer_parcial', models.DecimalField(decimal_places=2, max_digits=4)),
                ('segundo_parcial', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recuperacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
